# Generated by Django 3.2.14 on 2022-07-30 18:40

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields
import recipes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ingredient",
                    models.CharField(
                        max_length=200, verbose_name="Наименование ингредиента"
                    ),
                ),
                ("number", models.IntegerField(verbose_name="Колличество")),
                (
                    "unit_of_measure",
                    models.TextField(verbose_name="Единица измерения"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256, verbose_name="Наименование рецепта"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="posts/",
                        verbose_name="Картинка",
                    ),
                ),
                ("text", models.TextField(verbose_name="Описание рецепта")),
                (
                    "ingredients",
                    multiselectfield.db.fields.MultiSelectField(
                        max_length=200, verbose_name=recipes.models.Ingredient
                    ),
                ),
                (
                    "tags",
                    multiselectfield.db.fields.MultiSelectField(
                        max_length=200, verbose_name=recipes.models.Tag
                    ),
                ),
                (
                    "cooking_time",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinLengthValidator(1)
                        ],
                        verbose_name="Время приготовления (в минутах)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Название"),
                ),
                (
                    "color",
                    models.CharField(
                        max_length=256, verbose_name="Цвет в HEX"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=200,
                        unique=True,
                        verbose_name="Уникальный слаг",
                    ),
                ),
            ],
        ),
    ]
