# Generated by Django 3.2.14 on 2022-08-09 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_auto_20220809_1439"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="recipeingredient",
            unique_together={("ingredients", "recipe")},
        ),
    ]
