# Generated by Django 3.2.14 on 2022-08-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_shoppingcart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.PositiveIntegerField(verbose_name="Количество"),
        ),
    ]
