# Generated by Django 3.2.14 on 2022-08-14 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0011_auto_20220813_1413"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipeingredients",
                through="recipes.RecipeIngredient",
                to="recipes.Ingredient",
                verbose_name="Ингридиент",
            ),
        ),
        # migrations.AlterField(
        #     model_name='recipeingredient',
        #     name='ingredients',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.ingredient'),
        # ),
    ]
