# Generated by Django 3.2.14 on 2022-08-14 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0012_auto_20220814_0900"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeingredient",
            name="ingredient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient",
                to="recipes.ingredient",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="recipeingredient",
            unique_together={("ingredient", "recipe")},
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="ingredients",
        ),
    ]
